{% set name = "zasper" %}
{% set version = "1.1.0" %}
{% set tag = "v1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zasper-io/zasper/archive/refs/tags/{{ tag }}.tar.gz
  sha256: 593eee4f771890b34c342dc0cb0e784780135448cd7c8f50db2ddef2038a88cc


build:
  number: 0
  script:
    # go-licenses skips every dependency as standard library unless GOROOT is set
    - export GOROOT=$(go env GOROOT) && go-licenses save . --save_path=license-files --ignore github.com/zasper-io/zasper  # [unix]
    - go-licenses save . --save_path=license-files --ignore github.com/zasper-io/zasper  # [win]
    - make init
    - make build
    - install -m755 zasper "$PREFIX/bin/zasper"  # [not win]
    - copy /Y zasper.exe %PREFIX%\bin\zasper.exe  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]


requirements:
  build:
    - go >=1.25
    - nodejs >=22.12
    - make
    - go-licenses
  run:
    - python
    - ipykernel

test:
  commands:
    - zasper --version

about:
  home: https://github.com/zasper-io/zasper
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: "Zasper: High Performance IDE for Jupyter Notebooks"
  dev_url: https://github.com/zasper-io/zasper
  doc_url: https://zasper.io/docs

extra:
  recipe-maintainers:
    - prasunanand
